### PR TITLE
populate board after get button click

### PR DESCRIPTION
**Pull request by yzAlvin**
Open index.html

There is now a get button

Enter a board id

After pressing get, the board will populate with the board title, and it will create notes with the topic and dateCreated on them.

You need to enter a board id because getBoardByName does not work from what I can tell, it always returns 400 "BoardId is not valid". Once that method has been fixed, we could change line 235 and it will work with getBoardByName

### CODE REVIEW

**Comment by yzAlvin** [comment]
also no styling for the notes, I saw on stream you guys may have done that already? so if we just update the tag attributes the styling may get applied

**Comment by zainafzal88** [comment]
@toreylittlefield oh okay. Is this when you give an existing board name and press enter. Then it get all the notes associated with that board?

**Comment by toreylittlefield** [comment]
> @toreylittlefield oh okay. Is this when you give an existing board name and press enter. Then it get all the notes associated with that board?

Existing board? You mean create a new board?

**Comment by zainafzal88** [comment]
> > @toreylittlefield oh okay. Is this when you give an existing board name and press enter. Then it get all the notes associated with that board?
> 
> Existing board? You mean create a new board?

Existing board. So, when there is alreay a board saved and the user wants to see it few days later, they enter their board name and click "Get", it will then then the board, it's associated notes for them and populate them on `index.html`

**Comment by toreylittlefield** [comment]
> > > @toreylittlefield oh okay. Is this when you give an existing board name and press enter. Then it get all the notes associated with that board?
> > 
> > 
> > Existing board? You mean create a new board?
> 
> Existing board. So, when there is alreay a board saved and the user wants to see it few days later, they enter their board name and click "Get", it will then then the board, it's associated notes for them and populate them on `index.html`

OK wasn't aware of that I'll check it out and review.

**Comment by toreylittlefield** [comment]
> @toreylittlefield did you add a button "Get" too unless i missed seeing it
> 

No actually i don't see one only on the home.html where you create a board so i am confused again. Maybe this is for a new button to get a board on index.html?

**Comment by andreigec** [comment]
What a useful thread and pr :kappa

**Pull request closed without merging**
